language: node_js
node_js:
  - 14
addons:
  packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - eslint 'src/**'
  - npm run test:coveralls
  - npm run test:cypress:ci
build:
	provider: heroku
	api_key: $HEROKU_API
	app: clean-react-ts
	skip_cleanup: true
notifications:
  email: false